name: Create_issues_from_file
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: $({steps.step1.outputs.test})

    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
