name: Create issues from file
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{steps.contents.outputs.data}}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.9'

      - name: Run Python script
        id: contents
        run:
          contents=$( cat Text.txt )
          echo "::set-output name=data::$contents"
  job2: 
  	runs-on: ubuntu-latest
   	steps:
		- name: Create an issue
	        uses: JasonEtco/create-an-issue@v2.9.1
            
