name: Create issues from file
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{steps.contents.outputs.data}}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.9'

      - name: Run Python script
        id: contents
        run:
          contents=$( cat Text.txt )
          echo "::set-output name=data::$contents"
  job2: 
	  runs-on: ubuntu-latest
	  needs: job1
	  name: Issue Name ${{needs.job1.outputs.output1}}
	  steps: 
		  - uses: actions/add-to-project@develop
     		with:
        # You can target a project in a different organization
        # to the issue
		project-url: 		https://github.com/users/itimotin/projects/1
	  github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
	  labeled: bug
